name: Build Readme files

on:
  push:
    paths:
      - Files/**
      - scripts/**

permissions:
  contents: write

jobs:
  build-readme-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build 1_Basics.md
        run: python scripts/build_basics_readme.py

      - name: Build 2_OOPC.md
        run: python scripts/build_oopc_readme.py

      - name: Build 3_STL.md
        run: python scripts/build_stl_readme.py
        
      - name: Build 4_Other.md
        run: python scripts/build_other_readme.py        

      - name: Commit Readme Files
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add 1_Basics.md 2_OOPC.md 3_STL.md 4_Other.md
          git commit -m "Auto-update readme files"
          git push